#
version: '3.1'

services:

  cimitra:
    image: cimitra/free
    ports:
      - 81:80
      - 444:443
    restart: always
    #volumes:
    #  - ./mongo_data:/data/db
    working_dir: "/var/cimitra/api"
    environment:
      APPIT_DB_URL: mongodb://localhost/cimitra_prod
      NODE_ENV: production
      JWT_KEY: N0n30fYovrBus1n3ss!!_Dev
      MONGODB_BIN_PATH: /usr/bin
    entrypoint:
      - /bin/bash
      - /var/cimitra/api/wait.sh
